#!/usr/bin/env php
<?php
define('CMS_BASE_PATH', dirname(__FILE__) . '/');
define('CMS_PATH', CMS_BASE_PATH . 'Octo/');
define('IS_CONSOLE', true);

require_once(CMS_PATH . 'bootstrap.php');

$application = new Symfony\Component\Console\Application();

$paths = b8\Config::getInstance()->get('Octo.paths.namespaces');

foreach ($paths as $ns => $path) {
    $files = glob($path . 'Command/*.php');
    $path = $path . 'Command/';

    if (!is_dir($path)) {
        continue;
    }

    $di = new DirectoryIterator($path);

    foreach ($di as $file) {
        if ($file->getExtension() == 'php') {
            $command = $ns . '\\Command\\' . $file->getBasename('.php');
            $application->add(new $command());
        }
    }
}

$application->run();
