<section class="control-group {@ccss}{if error} error{/if}">
    {if label}<label class="label">{@label}</label>{/label}

    {if imageId}
        <div class="image_form_container">
            <p><img src="/media/render/{@imageId}/200/auto"></p>
            <label for="remove_{@name}"><input type="checkbox" value="1" name="remove_{@name}" id="remove_{@name}"> Remove current image</label>
        </div>
    {/if}

    <label class="input{if error} state-error{/if}">
        <input id="{@id}" type="{@type}" class="{@css}{if error} invalid{/if}" name="{@name}" value="{@value}"{if pattern} pattern="{@pattern}"{/if}{if required} required{/if}>
    </label>

    {if error}
        <em for="{@name}" class="invalid">{@error}</em>
    {/if}
</section>

